# .pre-commit-config.yaml
exclude: ^frontend/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        files: ^app/.*\.py$
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        files: ^app/.*\.py$
